### ISSUE TITLE
not showing up Turtle WoW

### ISSUE THREAD

**Issue by Dushku** [refaim/TNE-FiveSec-vanilla#1]
Downloaded ZIP. Extracted ZIP into /Interface/Addons. Renamed folder to lose the -master at the end, so it's now /Interface/Addons/TNE-FiveSec

It's not showing up in my addons. Every other mod I've added to Turtle WoW showed up right away. Please help. Readme makes no indication of naming/file structure.

**Comment by refaim** [comment]
It should be named `TNE_FiveSec`. I renamed the repository.
